name: sample
description: sample config file
source-dir: ./test/original
target-dir: ./test/revised
output-file:
ignore-files:
- class
- docx
- doc
file-types:
- extensions:
  - default
- extensions:
  - java
  plugins:
  - name: IgnoreRegularExpressionPlugin
    enabled: true
    parameters:
    - name: regexp
      value: ^@Generated\(.*
  - name: IgnoreMultilineCommentsPlugin
    enabled: true
  - name: IgnoreSingleLineCommentsPlugin
    enabled: true
  - name: IgnoreBlankPlugin
    enabled: true
- extensions:
  - xml
  - html
  plugins:
  - name: IgnoreXmlCommentsPlugin
    enabled: true
  - name: IgnoreBlankPlugin
    enabled: true